### PR TITLE
Configure Azure credentials using a service principal instead of DefaultAzureCredential

### LINKED ISSUE #480: [Azure] Error: Insufficient privileges to complete the operation
```
(base) ubuntu@ip-172-31-10-188:~/skyplane$ skyplane init --reinit-azure
 _____ _   ____   _______ _       ___   _   _  _____ 
/  ___| | / /\ \ / / ___ \ |     / _ \ | \ | ||  ___|
\ `--.| |/ /  \ V /| |_/ / |    / /_\ \|  \| || |__  
 `--. \    \   \ / |  __/| |    |  _  || . ` ||  __| 
/\__/ / |\  \  | | | |   | |____| | | || |\  || |___ 
\____/\_| \_/  \_/ \_|   \_____/\_| |_/\_| \_/\____/

03:52:00 [DEBUG] Found existing configuration file at /home/ubuntu/.skyplane/config, loading

(1) Configuring AWS:
    Do you want to configure AWS support in Skyplane? [Y/n]: 
    Loaded AWS credentials from the AWS CLI [IAM access key ID: ...BJTNGN]
    AWS region config file saved to /home/ubuntu/.skyplane/aws_config

(2) Configuring Azure:
    Do you want to configure Azure support in Skyplane? [Y/n]: 
    Azure credentials will be re-initialized
    I'll automatically create a Skyplane service principal for you. Do you want me to do this? (most common) [Y/n]: 
    Which Azure subscription ID do you want to use? [43ae1537-caa1-45b8-896f-f53228dab4cd]: 
    I will run the following commands to create an Azure service principal:
        $ az account set --subscription 43ae1537-caa1-45b8-896f-f53228dab4cd
        $ az ad sp create-for-rbac --name skyplane
     ⠇ Creating Skyplane service principal    Error running command: az ad sp create-for-rbac --name skyplane
    stdout: 
    stderr: ERROR: Insufficient privileges to complete the operation.

    Disabling Azure support

(3) Configuring GCP:
    Do you want to configure GCP support in Skyplane? [Y/n]: 
    GCP already configured! To reconfigure GCP, run `skyplane init --reinit-gcp`.

Config file saved to /home/ubuntu/.skyplane/config
```

### PR DESCRIPTION
**Pull request by parasj**
This PR solves many bugs caused from slow Azure role propagation. This PR uses service principals to authenticate with storage accounts.

This PR is a stacked PR with https://github.com/skyplane-project/skyplane/pull/478.

Fixes SKY-251
Fixes #480

### CODE REVIEW

**Comment by parasj** [comment]
This PR now works:

**Comment by parasj** [comment]
TODO: use rich spinners to clean up the Azure init flow
indent rich spinners to render well in the init flow

**Review by samkumar — APPROVED** [review]
Looks good to me. But I haven't actually run this code yet. If you'd like me to test it, please give me Azure credentials out of band so I can do that.

**Review by JasonDing0401 — APPROVED** [review]
LGTM! I have tested both transfers from azure to aws and azure to azure. They both work.

**Pull request merged**
