### PR TITLE
Fix Python 3.7 for config_paths

### LINKED ISSUE #667: [bug] Error `TypeError: Expected maxsize to be an integer or None` when running `skyplane`
**Describe the bug**
I pulled code from main and tried to run `skyplane init` but got an error. I also tried uninstalling my existing skyplane installation in my env and re-installing. 

**To Reproduce**
Run `skyplane init` or any `skyplane command`

**Expected behavior**
The error below appears: 
```
Traceback (most recent call last):
  File "/Users/sarahwooders/repos/skyplane/env/bin/skyplane", line 5, in <module>
    from skyplane.cli.cli import app
  File "/Users/sarahwooders/repos/skyplane/env/lib/python3.7/site-packages/skyplane/__init__.py", line 3, in <module>
    from skyplane import compute
  File "/Users/sarahwooders/repos/skyplane/env/lib/python3.7/site-packages/skyplane/compute/__init__.py", line 1, in <module>
    from skyplane.compute.aws.aws_auth import AWSAuthentication
  File "/Users/sarahwooders/repos/skyplane/env/lib/python3.7/site-packages/skyplane/compute/aws/aws_auth.py", line 4, in <module>
    from skyplane.config_paths import config_path, aws_config_path
  File "/Users/sarahwooders/repos/skyplane/env/lib/python3.7/site-packages/skyplane/config_paths.py", line 13, in <module>
    @functools.lru_cache
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/functools.py", line 490, in lru_cache
    raise TypeError('Expected maxsize to be an integer or None')
TypeError: Expected maxsize to be an integer or None
```

**Transfer client log**
No log. 

**Environment info (please complete the following information):**
 - OS: MacOS 
- Python version: 3.7.9

### PR DESCRIPTION
**Pull request by parasj**
Fixes #667

### CODE REVIEW

**Comment by sarahwooders** [comment]
I'm getting this error on skyplane init and cp: 
```
Traceback (most recent call last):
  File "/Users/sarahwooders/repos/skyplane/env/bin/skyplane", line 5, in <module>
    from skyplane.cli.cli import app
  File "/Users/sarahwooders/repos/skyplane/env/lib/python3.7/site-packages/skyplane/__init__.py", line 3, in <module>
    from skyplane import compute
  File "/Users/sarahwooders/repos/skyplane/env/lib/python3.7/site-packages/skyplane/compute/__init__.py", line 9, in <module>
    from skyplane.compute.gcp.gcp_cloud_provider import GCPCloudProvider
  File "/Users/sarahwooders/repos/skyplane/env/lib/python3.7/site-packages/skyplane/compute/gcp/gcp_cloud_provider.py", line 9, in <module>
    from skyplane.compute.gcp.gcp_network import GCPNetwork
  File "<fstring>", line 1
    (body=)
         ^
SyntaxError: invalid syntax
```

**Comment by parasj** [comment]
I can't install Python 3.7 on my Mac as it's ARM. I pushed another change to remove the unsupported fstring syntax. Can you try it one more time? I'm not able to test it locally.

There's a lot of small features that are unsupported on Python 3.7 that I added with the API PR.

**Comment by parasj** [comment]
(whoops, closed the PR by mistake)

**Comment by parasj** [comment]
@sarahwooders I think this should fix Python 3.7 issues, but please check if so!

**Comment by sarahwooders** [comment]
Yep was able to run `skyplane init`!

**Pull request merged**
