### PR TITLE
[UX] Print better error message when transfer validation fails

### LINKED ISSUE #508: Post-transfer Verification: Print out clearer message if verification fails
Setup: 
Start a long running transfer with `skyplane cp`. Then, delete some objects in the portal midway through the transfer.

Screen Shot 2022-08-30 at 4 03 32 PM

Once the post-transfer verification completes, the following error is printed:
Screen Shot 2022-08-30 at 4 02 56 PM

At the end of this error, we are informed that 5 objects failed verification. This message should be clearer, and we should print the names of these objects that failed.

### PR DESCRIPTION
**Pull request by liuxt129**
Fixes #508 

TransferFailedException raised by ReplicatorClient.verify_transfer_prefix() will now be caught in both cp and sync, and a detailed transfer failed message will be printed.
transfer_failed

### CODE REVIEW

**Comment by parasj** [comment]
@liuxt129 Before you merge, can you take a look and see why it says "Transfer successfully completed" and then immediately prints "Transfer failed exception"?

Also, the error message should be more descriptive and say something like "The following objects were not found at the destination"

**Comment by liuxt129** [comment]
The "Transfer successfully completed" message is printed in function [launch_replication_job](https://github.com/skyplane-project/skyplane/blob/07a1b8cb41c084ffbc2e4cf9173155c8bade5127/skyplane/cli/cli_impl/cp_replicate.py#L378-L382) in cp_replicate.py, before the verify is done.

If we don't want this to happen, I think we can move the success message part from cp_replicate.py to cli.py, after the verify passes. We have everything we need for the success message from `stats` returned from `launch_replication_job`

**Comment by liuxt129** [comment]
A more descriptive error message:
transfer_failed

**Comment by liuxt129** [comment]
New failed message:
transfer_failed

New success message:
transfer_succeeded

**Pull request merged**
