### PR TITLE
Accelerate multipart transfer requests

### LINKED ISSUE #571: Finalizing multipart transfers - need a spinner
Need to have a way to inform the user that we are verifying multi-part transfers through a spinner. Right now, it is hard to tell if skyplane failed silently, or is doing something in the background. 

image

### PR DESCRIPTION
**Pull request by parasj**
This is an exploratory PR to improve multipart transfer request setup latency. Multipart transfers take less than 10s to set up and under 1s to complete for 1k objects.

Fixes #571

### CODE REVIEW

**Comment by sarahwooders** [comment]
I tested this with the public bucket command `skyplane cp -r s3://imagenet-bucket s3://sarah-skylark-eu-north-1/imagenet-bucket` and the transfer worked, but the destination names are wrong. Not sure if this is related to this pull request specifically, but I get the error: 
```
TransferFailedException: 545 objects failed verification
Transfer failed. The following objects were not found at the destination: ['train-00000-of-01024', 'train-00001-of-01024' ....]
```
Checking my bucket, it looks like the "t" is missing: 
image

**Comment by antonzabreyko** [comment]
I also see the validation error on all of the files I transferred, and I checked the destination bucket and none of those files are there. Rerunning the benchmark on main does successfully transfer the files. 

Can you also summarize the changes you made to improve the setup latency?

**Comment by parasj** [comment]
@sarahwooders @antonzabreyko Can you try this transfer again? The latest set of commits should fix it.

**Comment by antonzabreyko** [comment]
I re-ran the benchmark and it is working now, but initiating the multipart uploads takes roughly 39 seconds, while on the main branch it takes 22 seconds. This is with a 100 140 MB file transfer. What was the improvement you saw with your benchmark?

**Comment by parasj** [comment]
@antonzabreyko I confirm this is slightly slower than the main branch, but it appears to not encounter problems with file limits now. I'll merge it but it's worth investigating how we can make it faster. I think one thing we can do is to finalize multipart transfers during the progress bar as objects complete.

**Pull request merged**
