### PR TITLE
azure: add 'tags' argument to provision_instance

### PR DESCRIPTION
**Pull request by phi-line**
I found this issue after seeing the latest integration test fail on GH actions:
https://github.com/skyplane-project/skyplane/actions/runs/3293577856

---

Also adds `autoflake` to poetry dev deps

### CODE REVIEW

**Review by parasj — APPROVED** [review]
@phi-line This is fantastic, thanks for submitting this! This does seem to fix the integration test. I can't get Github Actions to pass so I'm investigating ways to support this. Once tests pass, this should be good to merge.

**Comment by parasj** [comment]
@phi-line Thanks for the patience. I got it so I can trigger cloud unit tests against forks. Apologies for any spam on your branch. Feel free to merge when ready.

**Comment by phi-line** [comment]
@parasj thanks for fixing the issue with GH actions when triggered by forks. I noticed that we are using merge commits to update the branches to `HEAD` at `main`. It might leave a cleaner history to rebase these changes instead. Otherwise, we get a lot of messages like these:
image

> Feel free to merge when ready

I'm ready to merge but I do not have permissions. "Only those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to this repository can merge pull requests."

**Comment by parasj** [comment]
@phi-line Thanks, we squash and merge so maintaining clean history is usually not needed. This preserves linear history with original branch state in the PR. I just merged it, good to know that others cannot usually merge.

Thank you for your first contribution!

**Pull request merged**
