### PR TITLE
Multipart transfer

### PR DESCRIPTION
**Pull request by JasonDing0401**
1. Set `"multipart_enabled"` flag default to `True` in the config file;
2. When calculating the number of chunks in the multipart transfer, it now uses ceiling division so that there is no one more empty chunk if the file size is a multiple of the chunk size.

### CODE REVIEW

**Comment by parasj** [comment]
What was the issue with the ceiling division? What bug did you run where it didn't work properly. It looks like that was a bug but curious how you triggered the bug.

**Comment by JasonDing0401** [comment]
When I ran `skyplane cp -y s3://ap-se-2/random_file_4GB/random_file_4GB s3://eu-west-3/random_file_4GB` to transfer a large random file, skyplane will stripe it into small chunks. However, it errored that
```
(base) ubuntu@ip-172-31-10-188:~/skyplane$ skyplane cp -y s3://ap-se-2/random_file_4GB/random_file_4GB s3://eu-west-3/random_file_4GB
 _____ _   ____   _______ _       ___   _   _  _____ 
/  ___| | / /\ \ / / ___ \ |     / _ \ | \ | ||  ___|
\ `--.| |/ /  \ V /| |_/ / |    / /_\ \|  \| || |__  
 `--. \    \   \ / |  __/| |    |  _  || . ` ||  __| 
/\__/ / |\  \  | | | |   | |____| | | || |\  || |___ 
\____/\_| \_/  \_/ \_|   \_____/\_| |_/\_| \_/\____/


Will transfer 1 objects totaling 4.00GB from aws:ap-southeast-2 to aws:eu-west-3
    VMs to provision: 1x aws:ap-southeast-2, 1x aws:eu-west-3
    Estimated egress cost: $0.39 at $0.10/GB
    random_file_4GB/random_file_4GB => random_file_4GB

Storing debug information for transfer in /tmp/skyplane/transfer_logs/20220803_002209/client.log
✓ Initializing cloud keys (5/5) in 4.44s
✓ Provisioning gateway instances (2/2) in 38.38s
✓ Installing gateway package (2/2) in 19.32s
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/ubuntu/skyplane/skyplane/cli/cli.py:160 in cp                                              │
│                                                                                                  │
│   157 │   │   │   ask_to_confirm_transfer=not confirm,                                           │
│   158 │   │   )                                                                                  │
│   159 │   │                                                                                      │
│ ❱ 160 │   │   stats = launch_replication_job(                                                    │
│   161 │   │   │   topo=topo,                                                                     │
│   162 │   │   │   job=job,                                                                       │
│   163 │   │   │   debug=debug,                                                                   │
│                                                                                                  │
│ /home/ubuntu/skyplane/skyplane/cli/cli_impl/cp_replicate.py:265 in launch_replication_job        │
│                                                                                                  │
│   262 │   │   │   logger.fs.info(f"Log URLs for {gw.uuid()} ({node.region}:{node.instance})")    │
│   263 │   │   │   logger.fs.info(f"\tLog viewer: {gw.gateway_log_viewer_url}")                   │
│   264 │   │   │   logger.fs.info(f"\tAPI: {gw.gateway_api_url}")                                 │
│ ❱ 265 │   │   job = rc.run_replication_plan(                                                     │
│   266 │   │   │   job,                                                                           │
│   267 │   │   │   multipart_enabled=multipart_enabled,                                           │
│   268 │   │   │   multipart_max_chunk_size_mb=multipart_max_chunk_size_mb,                       │
│                                                                                                  │
│ /home/ubuntu/skyplane/skyplane/replicate/replicator_client.py:361 in run_replication_plan        │
│                                                                                                  │
│   358 │   │   │   │   │   │   for chunk in range(num_chunks):                                    │
│   359 │   │   │   │   │   │   │   # size is min(chunk_size, remaining data)                      │
│   360 │   │   │   │   │   │   │   file_size_bytes = min(chunk_size_bytes, src_object.size - of   │
│ ❱ 361 │   │   │   │   │   │   │   assert file_size_bytes > 0, f"File size <= 0 {file_size_byte   │
│   362 │   │   │   │   │   │   │   chunks.append(                                                 │
│   363 │   │   │   │   │   │   │   │   Chunk(                                                     │
│   364 │   │   │   │   │   │   │   │   │   src_key=src_object.key,                                │
│                                                                                                  │

AssertionError: File size <= 0 0
```
Because the file size (4GiB) is a multiple of chunk size (8MiB), doing `num_chunks = int(src_object.size / chunk_size_bytes) + 1` will have one empty chunk, which resulted that assertion error.
Hope this clarifies your question!

**Comment by parasj** [comment]
I queued an integration test run over this branch to verify it works. Please merge once this Github Action run completes successfully: https://github.com/skyplane-project/skyplane/actions/runs/2791401921

**Review by parasj — APPROVED** [review]
LGTM! Please wait for the integration test to pass before merging: https://github.com/skyplane-project/skyplane/actions/runs/2791401921

**Comment by parasj** [comment]
Integration tests passed, you should be good to merge this

**Pull request merged**
