### PR TITLE
Fix integration test on main, extract fallback CLI commands, add Azure fallback support and add sync fallback support

### PR DESCRIPTION
**Pull request by parasj**
Fixes: #553 

This PR makes several cleanups:
* Merge UsageClient logic for exceptions and usage
* Extract fallback command generation to another helper file
* Implement fallback commands for sync
* Implement fallback commands for Azure

Integration test rerun pending: https://github.com/skyplane-project/skyplane/actions/runs/3075774286

### CODE REVIEW

**Comment by ShishirPatil** [comment]
Breaks `skyplane cp` for s3 - s3 transfer


```
Traceback (most recent call last):
  File "/home/ubuntu/miniconda/bin/skyplane", line 8, in <module>
    sys.exit(app())
  File "/home/ubuntu/miniconda/lib/python3.8/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/home/ubuntu/miniconda/lib/python3.8/site-packages/click/core.py", line 1126, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/miniconda/lib/python3.8/site-packages/click/core.py", line 1051, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/miniconda/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/miniconda/lib/python3.8/site-packages/click/core.py", line 1393, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/miniconda/lib/python3.8/site-packages/click/core.py", line 752, in invoke
    return __callback(*args, **kwargs)
  File "/home/ubuntu/miniconda/lib/python3.8/site-packages/typer/main.py", line 500, in wrapper
    return callback(**use_params)  # type: ignore
  File "/home/ubuntu/skylark/skyplane/cli/cli.py", line 155, in cp
    src_client = ObjectStoreInterface.create(src_region_tag, bucket_src)
  File "/home/ubuntu/skylark/skyplane/obj_store/object_store_interface.py", line 109, in create
    raise ValueError(f"Invalid region_tag {region_tag} - could not create interface")
ValueError: Invalid region_tag s3:infer - could not create interface
```

**Review by JasonDing0401 — APPROVED** [review]
The changes in the performance logging client look good to me!

**Review by ShishirPatil — APPROVED** [review]
As a design choice `skyplane/cli/cli_impl/cp_replicate_fallback.py` introduces isolation but increases the surface area. Do we want to stick to this long term?

**Comment by parasj** [comment]
> As a design choice `skyplane/cli/cli_impl/cp_replicate_fallback.py` introduces isolation but increases the surface area. Do we want to stick to this long term?

We should eventually migrate off of this in the future, but I want to isolate this functionality so we can swap implementation as you implement improved on-prem functionality.

**Pull request merged**
