### PR TITLE
Feature: SCP (Samsung Cloud Platform) Support Contribution

### PR DESCRIPTION
**Pull request by sangjun-kang**
## Overview
This pull request adds support for [SCP (Samsung Cloud Platform) ](https://cloud.samsungsds.com/serviceportal/index.html)by implementing the necessary code. I have completed the development and testing phases and followed all the procedures outlined in the contributing guide.

## Details
- **Contributor:** sangjun-kang (aau213)
- https://github.com/skypilot-sds/skyplane/tree/scp-contribution
- **Branch:** scp-contribution

## Progress
- Code development and testing completed
- Issue and discussion registration
- Code review and adjustments

### CODE REVIEW

**Comment by sarahwooders** [comment]
@sangjun-kang could you please fix the formatting checks? You can run it with: 
```
pip install -r requirements-dev.txt
black -l 140 .
pytype --config .pytype.cfg skyplane
autoflake --in-place --remove-all-unused-imports --remove-unused-variables --recursive skyplane
```

**Comment by sangjun-kang** [comment]
> @sangjun-kang could you please fix the formatting checks? You can run it with:
> 
> ```
> pip install -r requirements-dev.txt
> black -l 140 .
> pytype --config .pytype.cfg skyplane
> autoflake --in-place --remove-all-unused-imports --remove-unused-variables --recursive skyplane
> ```

Hello @sarahwooders,

It seems that some parts were missed during the execution of the black formatting. 
I have re-run the checks, and everything should be in order now. 
Please review the changes, and let me know if there are any further adjustments needed.

Thank you!

**Comment by sarahwooders** [comment]
Thank you! Are there also any additional dependencies needed for SCP? If so, could you please update https://github.com/skyplane-project/skyplane/blob/main/pyproject.toml

**Comment by sangjun-kang** [comment]
> Thank you! Are there also any additional dependencies needed for SCP? If so, could you please update https://github.com/skyplane-project/skyplane/blob/main/pyproject.toml

Thank you for your comment! I've confirmed, and SCP doesn't require any additional dependencies beyond boto3. 
I've updated the [pyproject.toml](https://github.com/skyplane-project/skyplane/blob/main/pyproject.toml) to reflect the SCP section.
I appreciate your attention to detail. If you have any more questions or concerns, feel free to let me know!

**Comment by sarahwooders** [comment]
@sangjun-kang thanks for the update! I am having an additional issue with the configuration step (I modified the credentials files to have the right fields so it could be read) but now am getting this error: 

```
08:06:01 [DEBUG] Found existing configuration file at /Users/sarahwooders/.skyplane/config, loading

(1) Configuring AWS:
    AWS support disabled because boto3 is not installed. Run `pip install 'skyplane[aws]'`.

(2) Configuring Azure:
    Do you want to configure Azure support in Skyplane? [Y/n]: n
    Disabling Azure support

(3) Configuring GCP:
    Do you want to configure GCP support in Skyplane? [Y/n]: n
    Disabling Google Cloud support

(4) Configuring Cloudflare R2:
    Do you want to configure Cloudflare support in Skyplane? [Y/n]: n
    Disabling Cloudflare support

(5) Configuring SCP:
    Do you want to configure SCP support in Skyplane? [Y/n]: Y
True
    Loaded SCP credentials from the scp_credential [scp_access key: ...rad2Hk]
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /Users/sarahwooders/skyplane/skyplane/cli/cli_init.py:630 in init                                │
│                                                                                                  │
│   627 │   │   else:                                                                              │
│   628 │   │   │   typer.secho("\n(5) Configuring SCP:", fg="yellow", bold=True)                  │
│   629 │   │   if not disable_config_scp:                                                         │
│ ❱ 630 │   │   │   cloud_config = load_scp_config(cloud_config, force_init=reinit_scp, non_inte   │
│   631 │                                                                                          │
│   632 │   cloud_config.to_config_file(config_path)                                               │
│   633 │   typer.secho(f"\nConfig file saved to {config_path}", fg="green")                       │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │              cloud_config = SkyplaneConfig(                                                  │ │
│ │                             │   aws_enabled=False,                                           │ │
│ │                             │   azure_enabled=False,                                         │ │
│ │                             │   gcp_enabled=False,                                           │ │
│ │                             │   cloudflare_enabled=False,                                    │ │
│ │                             │   ibmcloud_enabled=False,                                      │ │
│ │                             │   scp_enabled=True,                                            │ │
│ │                             │   anon_clientid='00000000000000000000acde48001122',            │ │
│ │                             │   azure_principal_id=None,                                     │ │
│ │                             │   azure_subscription_id=None,                                  │ │
│ │                             │   azure_resource_group=None,                                   │ │
│ │                             │   azure_umi_name=None,                                         │ │
│ │                             │   azure_client_id=None,                                        │ │
│ │                             │   cloudflare_access_key_id='6c64c6fa3f582399b110cb1aceab149d', │ │
│ │                             │                                                                │ │
│ │                             cloudflare_secret_access_key='d57817c75e259b191da11def37feca040… │ │
│ │                             │   gcp_project_id=None,                                         │ │
│ │                             │   ibmcloud_access_id=None,                                     │ │
│ │                             │   ibmcloud_secret_key=None,                                    │ │
│ │                             │   ibmcloud_iam_key=None,                                       │ │
│ │                             │   ibmcloud_iam_endpoint=None,                                  │ │
│ │                             │   ibmcloud_useragent=None,                                     │ │
│ │                             │   ibmcloud_resource_group_id=None,                             │ │
│ │                             │   scp_access_key=None,                                         │ │
│ │                             │   scp_secret_key=None,                                         │ │
│ │                             │   scp_project_id=None                                          │ │
│ │                             )                                                                │ │
│ │        disable_config_aws = False                                                            │ │
│ │      disable_config_azure = False                                                            │ │
│ │ disable_config_cloudflare = False                                                            │ │
│ │        disable_config_gcp = False                                                            │ │
│ │        disable_config_ibm = True                                                             │ │
│ │        disable_config_scp = False                                                            │ │
│ │           non_interactive = False                                                            │ │
│ │              reinit_azure = False                                                            │ │
│ │         reinit_cloudflare = False                                                            │ │
│ │                reinit_gcp = False                                                            │ │
│ │                reinit_ibm = False                                                            │ │
│ │                reinit_scp = False                                                            │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ /Users/sarahwooders/skyplane/skyplane/cli/cli_init.py:520 in load_scp_config                     │
│                                                                                                  │
│   517 │   │   │   │   f"    Loaded SCP credentials from the scp_credential [scp_access key: ..   │
│   518 │   │   │   │   fg="blue",                                                                 │
│   519 │   │   │   )                                                                              │
│ ❱ 520 │   │   │   auth.save_region_config(config)                                                │
│   521 │   │   │   typer.secho(f"    SCP region config file saved to {scp_config_path}", fg="bl   │
│   522 │   │   │   config.scp_enabled = True                                                      │
│   523 │   │   │   return config                                                                  │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │                auth = <skyplane.compute.scp.scp_auth.SCPAuthentication object at             │ │
│ │                       0x12418b510>                                                           │ │
│ │              config = SkyplaneConfig(                                                        │ │
│ │                       │   aws_enabled=False,                                                 │ │
│ │                       │   azure_enabled=False,                                               │ │
│ │                       │   gcp_enabled=False,                                                 │ │
│ │                       │   cloudflare_enabled=False,                                          │ │
│ │                       │   ibmcloud_enabled=False,                                            │ │
│ │                       │   scp_enabled=True,                                                  │ │
│ │                       │   anon_clientid='00000000000000000000acde48001122',                  │ │
│ │                       │   azure_principal_id=None,                                           │ │
│ │                       │   azure_subscription_id=None,                                        │ │
│ │                       │   azure_resource_group=None,                                         │ │
│ │                       │   azure_umi_name=None,                                               │ │
│ │                       │   azure_client_id=None,                                              │ │
│ │                       │   cloudflare_access_key_id='6c64c6fa3f582399b110cb1aceab149d',       │ │
│ │                       │                                                                      │ │
│ │                       cloudflare_secret_access_key='d57817c75e259b191da11def37feca0409d0b2d… │ │
│ │                       │   gcp_project_id=None,                                               │ │
│ │                       │   ibmcloud_access_id=None,                                           │ │
│ │                       │   ibmcloud_secret_key=None,                                          │ │
│ │                       │   ibmcloud_iam_key=None,                                             │ │
│ │                       │   ibmcloud_iam_endpoint=None,                                        │ │
│ │                       │   ibmcloud_useragent=None,                                           │ │
│ │                       │   ibmcloud_resource_group_id=None,                                   │ │
│ │                       │   scp_access_key=None,                                               │ │
│ │                       │   scp_secret_key=None,                                               │ │
│ │                       │   scp_project_id=None                                                │ │
│ │                       )                                                                      │ │
│ │    credentials_path = '~/.scp/scp_credential'                                                │ │
│ │     credentials_scp = {                                                                      │ │
│ │                       │   'scp_access_key': 'vopeGAR2rHS5derad2Hk',                          │ │
│ │                       │   'scp_secret_key': 'cmFkMkhreFBFWmI1OW9lU3IvbkRXWWVESmxvNU09',      │ │
│ │                       │   'scp_project_id': 'PROJECT-64jZ7_TGtYjV_ONgMKukSa'                 │ │
│ │                       }                                                                      │ │
│ │ disable_scp_support = <function load_scp_config.<locals>.disable_scp_support at 0x12413ad40> │ │
│ │                   f = <_io.TextIOWrapper name='/Users/sarahwooders/.scp/scp_credential'      │ │
│ │                       mode='r' encoding='UTF-8'>                                             │ │
│ │          force_init = False                                                                  │ │
│ │                 key = 'scp_project_id'                                                       │ │
│ │                line = 'scp_project_id = PROJECT-64jZ7_TGtYjV_ONgMKukSa'                      │ │
│ │               lines = [                                                                      │ │
│ │                       │   'scp_access_key = vopeGAR2rHS5derad2Hk',                           │ │
│ │                       │   'scp_secret_key = cmFkMkhreFBFWmI1OW9lU3IvbkRXWWVESmxvNU09',       │ │
│ │                       │   'scp_project_id = PROJECT-64jZ7_TGtYjV_ONgMKukSa'                  │ │
│ │                       ]                                                                      │ │
│ │     non_interactive = False                                                                  │ │
│ │               value = 'PROJECT-64jZ7_TGtYjV_ONgMKukSa'                                       │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ /Users/sarahwooders/skyplane/skyplane/compute/scp/scp_auth.py:60 in save_region_config           │
│                                                                                                  │
│    57 │   │   if self.config.scp_enabled == False:                                               │
│    58 │   │   │   self.clear_region_config()                                                     │
│    59 │   │   │   return                                                                         │
│ ❱  60 │   │   region_list = self.get_region_config()                                             │
│    61 │   │                                                                                      │
│    62 │   │   with open(scp_config_path, "w") as f:                                              │
│    63 │   │   │   for region in region_list:                                                     │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │ config = SkyplaneConfig(                                                                     │ │
│ │          │   aws_enabled=False,                                                              │ │
│ │          │   azure_enabled=False,                                                            │ │
│ │          │   gcp_enabled=False,                                                              │ │
│ │          │   cloudflare_enabled=False,                                                       │ │
│ │          │   ibmcloud_enabled=False,                                                         │ │
│ │          │   scp_enabled=True,                                                               │ │
│ │          │   anon_clientid='00000000000000000000acde48001122',                               │ │
│ │          │   azure_principal_id=None,                                                        │ │
│ │          │   azure_subscription_id=None,                                                     │ │
│ │          │   azure_resource_group=None,                                                      │ │
│ │          │   azure_umi_name=None,                                                            │ │
│ │          │   azure_client_id=None,                                                           │ │
│ │          │   cloudflare_access_key_id='6c64c6fa3f582399b110cb1aceab149d',                    │ │
│ │          │                                                                                   │ │
│ │          cloudflare_secret_access_key='d57817c75e259b191da11def37feca0409d0b2d1ce084927bc90… │ │
│ │          │   gcp_project_id=None,                                                            │ │
│ │          │   ibmcloud_access_id=None,                                                        │ │
│ │          │   ibmcloud_secret_key=None,                                                       │ │
│ │          │   ibmcloud_iam_key=None,                                                          │ │
│ │          │   ibmcloud_iam_endpoint=None,                                                     │ │
│ │          │   ibmcloud_useragent=None,                                                        │ │
│ │          │   ibmcloud_resource_group_id=None,                                                │ │
│ │          │   scp_access_key=None,                                                            │ │
│ │          │   scp_secret_key=None,                                                            │ │
│ │          │   scp_project_id=None                                                             │ │
│ │          )                                                                                   │ │
│ │   self = <skyplane.compute.scp.scp_auth.SCPAuthentication object at 0x12418b510>             │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ /Users/sarahwooders/skyplane/skyplane/compute/scp/scp_auth.py:80 in get_region_config            │
│                                                                                                  │
│    77 │                                                                                          │
│    78 │   @staticmethod                                                                          │
│    79 │   def get_region_config() -> List[str]:                                                  │
│ ❱  80 │   │   zones = SCPAuthentication.get_zones()                                              │
│    81 │   │   # print(zones)                                                                     │
│    82 │   │   service_zone_locations = [zone["serviceZoneName"] for zone in zones]               │
│    83 │   │   return service_zone_locations                                                      │
│                                                                                                  │
│ /Users/sarahwooders/skyplane/skyplane/compute/scp/scp_auth.py:75 in get_zones                    │
│                                                                                                  │
│    72 │   │   scp_client = SCPClient()                                                           │
│    73 │   │   url = f"/project/v3/projects/{scp_client.project_id}/zones"                        │
│    74 │   │                                                                                      │
│ ❱  75 │   │   response = scp_client._get(url)                                                    │
│    76 │   │   return response                                                                    │
│    77 │                                                                                          │
│    78 │   @staticmethod                                                                          │
│                                                                                                  │
│ ╭─────────────────────────────────── locals ────────────────────────────────────╮                │
│ │ scp_client = <skyplane.compute.scp.scp_utils.SCPClient object at 0x1241a8090> │                │
│ │        url = '/project/v3/projects/PROJECT-64jZ7_TGtYjV_ONgMKukSa/zones'      │                │
│ ╰───────────────────────────────────────────────────────────────────────────────╯                │
│                                                                                                  │
│ /Users/sarahwooders/skyplane/skyplane/compute/scp/scp_utils.py:104 in method_with_retries        │
│                                                                                                  │
│   101 │   │   │   │   else:                                                                      │
│   102 │   │   │   │   │   # with open(f"/skyplane/retry_nocode_error.txt", "w") as f:            │
│   103 │   │   │   │   │   #     f.write(str(e))                                                  │
│ ❱ 104 │   │   │   │   │   raise e                                                                │
│   105 │                                                                                          │
│   106 │   return method_with_retries                                                             │
│   107                                                                                            │
│                                                                                                  │
│ ╭──────────────────────────────────── locals ────────────────────────────────────╮               │
│ │        args = ('/project/v3/projects/PROJECT-64jZ7_TGtYjV_ONgMKukSa/zones',)   │               │
│ │   backoff_s = 1                                                                │               │
│ │      kwargs = {}                                                               │               │
│ │   max_tries = 60                                                               │               │
│ │      method = <function SCPClient._get at 0x11ff339c0>                         │               │
│ │ retry_codes = ['500', '412', '403']                                            │               │
│ │        self = <skyplane.compute.scp.scp_utils.SCPClient object at 0x1241a8090> │               │
│ │   try_count = 0                                                                │               │
│ ╰────────────────────────────────────────────────────────────────────────────────╯               │
│                                                                                                  │
│ /Users/sarahwooders/skyplane/skyplane/compute/scp/scp_utils.py:79 in method_with_retries         │
│                                                                                                  │
│    76 │   │   try_count = 0                                                                      │
│    77 │   │   while try_count < max_tries:                                                       │
│    78 │   │   │   try:                                                                           │
│ ❱  79 │   │   │   │   return method(self, *args, **kwargs)                                       │
│    80 │   │   │   except Exception as e:                                                         │
│    81 │   │   │   │   # print(e.args[0])                                                         │
│    82 │   │   │   │   retry_codes = ["500", "412", "403"]  # add 403 for object storage          │
│                                                                                                  │
│ ╭──────────────────────────────────── locals ────────────────────────────────────╮               │
│ │        args = ('/project/v3/projects/PROJECT-64jZ7_TGtYjV_ONgMKukSa/zones',)   │               │
│ │   backoff_s = 1                                                                │               │
│ │      kwargs = {}                                                               │               │
│ │   max_tries = 60                                                               │               │
│ │      method = <function SCPClient._get at 0x11ff339c0>                         │               │
│ │ retry_codes = ['500', '412', '403']                                            │               │
│ │        self = <skyplane.compute.scp.scp_utils.SCPClient object at 0x1241a8090> │               │
│ │   try_count = 0                                                                │               │
│ ╰────────────────────────────────────────────────────────────────────────────────╯               │
│                                                                                                  │
│ /Users/sarahwooders/skyplane/skyplane/compute/scp/scp_utils.py:145 in _get                       │
│                                                                                                  │
│   142 │   │   self.set_signature(url=url, method=method)                                         │
│   143 │   │                                                                                      │
│   144 │   │   response = requests.get(url, headers=self.headers)                                 │
│ ❱ 145 │   │   raise_scp_error(response)                                                          │
│   146 │   │                                                                                      │
│   147 │   │   if contents_key is not None:                                                       │
│   148 │   │   │   return response.json().get(contents_key, [])                                   │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │ contents_key = 'contents'                                                                    │ │
│ │       method = 'GET'                                                                         │ │
│ │     response = <Response [401]>                                                              │ │
│ │         self = <skyplane.compute.scp.scp_utils.SCPClient object at 0x1241a8090>              │ │
│ │          url = 'https://openapi.samsungsdscloud.com/project/v3/projects/PROJECT-64jZ7_TGtYj… │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ /Users/sarahwooders/skyplane/skyplane/compute/scp/scp_utils.py:70 in raise_scp_error             │
│                                                                                                  │
│    67 │   │   # print(f"response: {response.content}")                                           │
│    68 │   │   raise SCPClientError(f"Unexpected error. Status code: {status_code}")              │
│    69 │                                                                                          │
│ ❱  70 │   raise SCPClientError(f"{status_code}: {message}")                                      │
│    71                                                                                            │
│    72                                                                                            │
│    73 def _retry(method, max_tries=60, backoff_s=1):                                             │
│                                                                                                  │
│ ╭──────────────────────────────────────── locals ────────────────────────────────────────╮       │
│ │     message = '인증 방식이나 IP주소가 허용되지 않습니다.'                              │       │
│ │   resp_json = {                                                                        │       │
│ │               │   'service': 'GW',                                                     │       │
│ │               │   'timestamp': '2023-12-19T13:06:11.675Z',                             │       │
│ │               │   'contactUrl': 'https://cloud.samsungsds.com',                        │       │
│ │               │   'message': '인증 방식이나 IP주소가 허용되지 않습니다.',              │       │
│ │               │   'status': 401,                                                       │       │
│ │               │   'code': 'PLATFORM-IAM-000105',                                       │       │
│ │               │   'path': '/project/v3/projects/PROJECT-64jZ7_TGtYjV_ONgMKukSa/zones', │       │
│ │               │   'requestId': 'REQUEST-FCB778B7DD154B2AA31EC63D5BAD3172'              │       │
│ │               }                                                                        │       │
│ │    response = <Response [401]>                                                         │       │
│ │ status_code = 401                                                                      │       │
│ ╰────────────────────────────────────────────────────────────────────────────────────────╯       │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
SCPClientError: 401: 인증 방식이나 IP주소가 허용되지 않습니다.
```

**Comment by sangjun-kang** [comment]
Sorry, Sarah. The authentication key shared by Suk-hoon had IP restrictions (for security reasons). Suk-hoon has removed the IP restrictions, so please test it again. Also, there is authentication key information in the logs, so it would be great if you could erase the logs.

**Comment by dreamersnme** [comment]
> nk you for your comment! I've confirmed, and SCP doesn't require any additional dependencies beyond boto3.
> I've updated the [pyproject.toml](https://github.com/skyplane-project/skyplane/pull/926/commits/f035a49b4df2cec0f05c9fcac9f7602247dc3a9b) to reflect the SCP section.
> I appreciate your attention to detail. If you have any more questions or concerns, feel free to let me kno

@sarahwooders, @sangjun-kang , This error is due to the security settings of my account. sorry.
I've changed the settings so you can access now. 

By the way, you mentioned that there was an error in the credential format.
could you pinpoint where the error occurs?

**Comment by sarahwooders** [comment]
I just deleted the comment, and the `skyplane init` command worked now, thanks!

**Comment by sangjun-kang** [comment]
@sarahwooders, I encountered errors in the following files when running `pytype --config .pytype.cfg skyplane`, but these are not files I have committed, so I couldn't address them. Please take a look:

```
skyplane/gateway/gateway_queue.py
skyplane/gateway/operators/gateway_receiver.py
skyplane/gateway/gateway_daemon_api.py
skyplane/obj_store/hdfs_interface.py
skyplane/obj_store/r2_interface.py
skyplane/cli/cli_cloud.py
skyplane/gateway/operators/gateway_operator.py
skyplane/cli/impl/progress_bar.py
skyplane/planner/planner.py
```

**Comment by sarahwooders** [comment]
@sangjun-kang sorry for the delayed response, have been traveling! I can take a look at the pytest issues this week.

**Comment by sarahwooders** [comment]
Could you run `poetry run black -l 140 .`? I can also fix the formatting if you give me push permissions on your repo.

**Comment by sangjun-kang** [comment]
> Could you run `poetry install --with dev` and `poetry run black -l 140 .`? I can also fix the formatting if you give me push permissions on your repo. On my end, it only changed two files.

Hi @sarahwooders

I made changes to the SCP Object Storage API yesterday, adjusting some source code. It seems black formatting was missed, so I ran it again and committed the changes. 
And I've granted you repo access. Let me know if you need anything else.

Thanks,

**Review by sarahwooders — APPROVED** [review]
This now works for me - thank you so much for the contribution! I'll merge once the tests re-run.

**Pull request merged**
