### PR TITLE
Fix #827 #907 #908 #901, add compress operator and encrypt operator

### PR DESCRIPTION
**Pull request by killerdbob**
https://github.com/skyplane-project/skyplane/issues/901

@sarahwooders

### CODE REVIEW

**Comment by killerdbob** [comment]
fix https://github.com/skyplane-project/skyplane/pull/827,

**Comment by killerdbob** [comment]
commit [ae9a422](https://github.com/skyplane-project/skyplane/pull/906/commits/ae9a42200b8a87893007b7d4269c2f21b2679e8a), fix https://github.com/skyplane-project/skyplane/issues/908

**Review by sarahwooders — CHANGES_REQUESTED** [review]
Would it be possible to remove the advanced planner portions of your commit? I think it would be easier to track changes if we made one major change at a time, and the new planners will also need more extensive testing. 

Also, could you please make sure all the tests pass in the check?

**Comment by killerdbob** [comment]
ok, I will open another thread.

> Would it be possible to remove the advanced planner portions of your commit? I think it would be easier to track changes if we made one major change at a time, and the new planners will also need more extensive testing.
> 
> Also, could you please make sure all the tests pass in the check?

**Pull request closed without merging**
