### PR TITLE
disable OS Login by default for GCP VMs

### PR DESCRIPTION
**Pull request by troycarlson**
If [OS Login](https://cloud.google.com/compute/docs/oslogin) is enabled in a GCP project, new VMs will be created with OS Login enabled by default. When OS Login is enabled, `skyplane` is unable to establish an SSH connection to the VM. Disabling OS Login (when allowed by the GCP org) allows SSH connections via public key, and `skyplane` is able to connect.

**Steps to reproduce OS Login issue:**
1. [Enable OS Login in a GCP project](https://cloud.google.com/compute/docs/oslogin/set-up-oslogin#enable_os_login)
2. Run a Skyplane task which results in a GCP VM being provisioned
3. The task should fail with an error related to establishing an SSH connection

So the provisioning succeeds, but attempting to connect to the instance will fail. If you connect to the GCP VM directly (because it does not get de-provisioned in this failure mode) and run `sudo journalctl -u sshd` there will also be an error logged containing the message `Invalid user skyplane`. What seems to be happening is that when OS Login is enabled, SSH connections are rejected unless the user is known to OS Login.

If OS Login is [required at the GCP organization level](https://cloud.google.com/compute/docs/oslogin/manage-oslogin-in-an-org#set-org-policy) then the provisioning process itself should fail.  This seems fine because it doesn't appear Skyplane can support provisioning and connecting to VMs if OS Login is enabled, so the tool can consider disabling OS Login a requirement and the error message seems appropriate. If Skyplane can support connecting to a VM with OS Login enabled then this approach may not be sufficient and could be misleading in some cases.

### CODE REVIEW

**Review by parasj — APPROVED** [review]
LGTM! I verified that this continues to work with OS Login disabled account-wide.

**Comment by parasj** [comment]
Thanks for submitting a contribution to Skyplane! I wasn't aware of this organizational policy. OS Login appears to be safer than key-based authentication to VMs so we could consider migrating GCP VM execution to OS Login at some point in the future.

**Comment by parasj** [comment]
Minor nit: this branch isn't passing our style checker, can you run:
```
$ pip install black
$ black -l 140 .
```

which will result in the following patch:
```patch
diff --git a/skyplane/compute/gcp/gcp_cloud_provider.py b/skyplane/compute/gcp/gcp_cloud_provider.py
index 09caacb..1b3906d 100644
--- a/skyplane/compute/gcp/gcp_cloud_provider.py
+++ b/skyplane/compute/gcp/gcp_cloud_provider.py
@@ -164,7 +164,10 @@ class GCPCloudProvider(CloudProvider):
             ],
             "serviceAccounts": [{"email": "default", "scopes": ["https://www.googleapis.com/auth/cloud-platform"]}],
             "metadata": {
-                "items": [{"key": "enable-oslogin", "value": "false"}, {"key": "ssh-keys", "value": f"{gcp_vm_uname}:{self.key_manager.get_public_key(self.key_name).read_text()}\n"}]
+                "items": [
+                    {"key": "enable-oslogin", "value": "false"},
+                    {"key": "ssh-keys", "value": f"{gcp_vm_uname}:{self.key_manager.get_public_key(self.key_name).read_text()}\n"},
+                ]
             },
             "scheduling": {"onHostMaintenance": "TERMINATE", "automaticRestart": False},
             "deletionProtection": False,

```

**Comment by troycarlson** [comment]
> Minor nit: this branch isn't passing our style checker, can you run:
> 
> ```
> $ pip install black
> $ black -l 140 .
> ```
> 
> which will result in the following patch:
> 
> ```diff
> diff --git a/skyplane/compute/gcp/gcp_cloud_provider.py b/skyplane/compute/gcp/gcp_cloud_provider.py
> index 09caacb..1b3906d 100644
> --- a/skyplane/compute/gcp/gcp_cloud_provider.py
> +++ b/skyplane/compute/gcp/gcp_cloud_provider.py
> @@ -164,7 +164,10 @@ class GCPCloudProvider(CloudProvider):
>              ],
>              "serviceAccounts": [{"email": "default", "scopes": ["https://www.googleapis.com/auth/cloud-platform"]}],
>              "metadata": {
> -                "items": [{"key": "enable-oslogin", "value": "false"}, {"key": "ssh-keys", "value": f"{gcp_vm_uname}:{self.key_manager.get_public_key(self.key_name).read_text()}\n"}]
> +                "items": [
> +                    {"key": "enable-oslogin", "value": "false"},
> +                    {"key": "ssh-keys", "value": f"{gcp_vm_uname}:{self.key_manager.get_public_key(self.key_name).read_text()}\n"},
> +                ]
>              },
>              "scheduling": {"onHostMaintenance": "TERMINATE", "automaticRestart": False},
>              "deletionProtection": False,
> ```

Done

**Pull request merged**
