### PR TITLE
Interrupting Transfers Mid-way

### PR DESCRIPTION
**Pull request by HaileyJang**
This PR interrupts transfers mid-way by catching KeyboardInterrupt Exception.

When a KeyboardInterrupt is raised, it will exit the current task and deprovision (if gateway is not being reused). For handling parallel tasks, we send an exception to the thread, where the thread will handle the KeyboardInterrupt when it gets scheduled to run. 

Since multiple threads can be scheduled and take time to run, it may take few seconds to notify all the threads and all the threads to finish cleaning up their current task, so a few seconds delay in the CLI can occur.

### CODE REVIEW

**Comment by HaileyJang** [comment]
There is a bug where if you halt midway through provisioning, it will not deprovision the gateway that has been provisioned already. This is due to the fact that we wait for all the nodes to finish provisioning before we add it to the list of provisioned nodes, and that is why deprovisioning is not happening.

**Comment by parasj** [comment]
@HaileyJang @ShishirPatil We should have a whiteboard walkthrough to understand different failure points for a transfer. Ideally, we should understand how to minimize exit locations via better API usage. I don't think multithreading should create too much of an issue with regards to passing the KeyboardInterrupt. W/r to interrupting a transfer during provisioning, I added a pointer to store temporarily allocated nodes but I'm not sure how reliable that functionality is.

**Comment by parasj** [comment]
@abiswal2001 @JasonDing0401 Can you comment on how we could simplify this VM cleanup issue via the api's `skyplane.autoterminate()` manager? Would that improve the situation here?

**Comment by ShishirPatil** [comment]
@parasj,  @HaileyJang  and I had a discussion and this is my thought process:

An user might choose to interrupt the transfer due to any of the following reasons:

- Forgot to use the right flags
- Wants to modify the src/dst bucket
- Realized transfer is no longer required
- Parts of the transfer are taking too long
- etc

A transfer can be interrupted during any of the steps. Here, I list out the state-machine once an interrupt is called. 

a) Just after starting the transfer when we are in the VM provisioning phase. An interrupt here should add the list of VM(s) if we have the id's to a list and fall back to deprovisioning those VMs. If we are in posession of no VM ID's to deprovision then, we just exit. For more context refer (d)
b) While applying firewall rules, etc : We stop all ongoing tasks, and call deprovision on all the VM IDs (and associated resources like resource-groups). 
c) When the transfers have started : Do NOT wait till the chunks in flight arrive. Start deprovisioning VMs as above.
d) While de-provisioning VMs. This is an interesting case. My argument is that if a user wants to interrupt the deprovisioning task - we need to immediately SIGKILL whatever process skyplane has and return to the user. (Even in the case if we tried to interrupt a deprovisioing that was invoked due to a,b or c above.) The rationale behind this is that perhaps the user believes that the deprovisioning is taking too long, or there might be a bug in the system, and wants to regain control. Now this leaves the undesirable state of a malformed VMs (and malformed resource-groups, and networking interfaces in the worst case), but that is OK, since we want to have `skyplane deprovision` as the tool to clean it up. This is better than the worst case scenario - where the user is trying to interrupt skyplane, but skyplane is stuck in deprovisoning for 20+ minutes, as we sometimes observe.

Thoughts?

**Comment by parasj** [comment]
I recommend closing this issue as we migrate from the API to the CLI. Failure points should be minimal with the interruption logic. I would very much like to avoid the problem of leaked VMs and therefore do not like allowing users to support exiting during a deprovision option. I'm augmenting #548 with a note about a proposed confirmation dialog during KeyboardInterrupt when an existing deprovision operation is going on.

**Pull request closed without merging**
