### PR TITLE
Add support for downloading a list of URLs in Skyplane for pangeo

### PR DESCRIPTION
**Pull request by xutingl**
Add a new command `skyplane download-pangeo s3://...` that downloads all pangeo files (8187 URLs, each is about 30 MB) to the S3 bucket.

Not fully tested yet and has some hard-coded statements.

### CODE REVIEW

**Review by phi-line — CHANGES_REQUESTED** [review]
@xutingl Adding an integration with `pangeo` seems to be outside of the core functionality of the skyplane project. I would recommend making a separate repo that implements the skyplane core to facilitate your use-case, but I don't skyplane should have any associations to `pangeo` in the code repo.

@parasj what are your thoughts? I don't want to overstep if there's some larger plan behind this.

**Comment by parasj** [comment]
Hey @phi-line, we are collaborating with some folks working with Fernando Perez to see if we can make Pangeo Forge (data loaders for the pangeo system) faster using Skyplane. To support that, we would need to support an HTTP object store connector (i.e. download a list of files via URLs). This PR is an initial exploration to get a benchmark of how much faster Skyplane would be.

I agree that if successful, we would extract this logic into an external repo. More broadly, I'd actually rather see support for this use case via the API where integrations would be upstreamed to Pangeo Forge. The dataplane components would stay in Skyplane (e.g. HTTPInferface). But given the absolutely massive stock of data in NOAA/NASA/ESA data sources, I would like to help academics access big datasets more easily.

**Comment by phi-line** [comment]
@parasj What are your thoughts on making an `examples` file that could contain [`pangeo_util.py`](https://github.com/skyplane-project/skyplane/pull/653/files#diff-f60f167d33aaf77a6600442c5e622d05c49ef2123577ce33e3c832e7582571af)? This would keep the new code outside of the cli while still providing all the code to your users in a single repo.

**Comment by parasj** [comment]
@xutingl Let's hold off on merging this to main until we have a chance to clean this PR up further.

**Comment by parasj** [comment]
@xutingl I'm going to close this for now. We should add support for this once @sarahwooders lands the UDF support into the gateways. We can then simply write a UDF to bulk download files.

**Pull request closed without merging**
