### PR TITLE
Clean AWS provisioning logic to prepare for debugging concurrent Skyplane usage

### PR DESCRIPTION
**Pull request by parasj**
This is necessary for the Sky camp workshop.

Changes:
* Shift from random UUIDs to consistent machine IDs
* Extract networking logic to AWSNetwork
* Extract key management logic to AWSKeyManager
* Extract pricing logic to AWSPricing

### CODE REVIEW

**Comment by parasj** [comment]
@JasonDing0401 Please quickly review the changes I made to config.py in order to make UUIDs consistent. I will use these for key generation for AWS, so they should be consistent and always set.

**Comment by parasj** [comment]
@ShishirPatil Please review the changes to `aws_cloud_provider` carefully since I extracted network logic into a separate function. For Sky camp, I will probably want to provision different resource scopes across people. I also want to make deprovision only remove a user's own VMs, and only delete VPCs when they run `skyplane deprovision --all`.

**Review by JasonDing0401 — COMMENTED** [review]
LGTM! Do we need to consider the case when `get_node()` fails and returns a random integer?

**Comment by parasj** [comment]
@JasonDing0401 I think getnode will always return something but may not be consistent with multiple network interfaces. Since we write it to the config file, it should be consistent though.

**Pull request merged**
